package com.chestlogger.web;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;

class WebConfigTest {

    @Test
    @DisplayName("Should have strict secure defaults (disabled by default, 127.0.0.1 host binding, port 8080)")
    void testSecureDefaults() {
        WebConfig config = new WebConfig();

        assertThat(config.isEnabled()).isFalse(); // Security: Must be disabled by default
        assertThat(config.getHost()).isEqualTo("127.0.0.1"); // Security: Localhost binding only by default
        assertThat(config.getPort()).isEqualTo(8080);
        assertThat(config.getSecretToken()).isNotNull().isNotEmpty();
    }

    @Test
    @DisplayName("Should serialize to JSON and deserialize back correctly preserving settings")
    void testSaveAndLoad(@TempDir Path tempDir) throws IOException {
        File configFile = tempDir.resolve("chestlogger_web.json").toFile();

        WebConfig original = new WebConfig(true, "0.0.0.0", 9090, "super_secret_token_123", "http://localhost:3000", 30);
        original.save(configFile);

        assertThat(configFile.exists()).isTrue();

        WebConfig loaded = WebConfig.load(configFile);
        assertThat(loaded.isEnabled()).isTrue();
        assertThat(loaded.getHost()).isEqualTo("0.0.0.0");
        assertThat(loaded.getPort()).isEqualTo(9090);
        assertThat(loaded.getSecretToken()).isEqualTo("super_secret_token_123");
        assertThat(loaded.getAllowedOrigins()).isEqualTo("http://localhost:3000");
        assertThat(loaded.getMaxConnections()).isEqualTo(30);
    }

    @Test
    @DisplayName("Should auto-generate secure random secretToken on new config generation")
    void testAutoGeneratedToken(@TempDir Path tempDir) {
        File configFile = tempDir.resolve("new_config.json").toFile();

        WebConfig loaded = WebConfig.load(configFile);
        assertThat(loaded.getSecretToken()).hasSize(32);
        assertThat(loaded.isEnabled()).isFalse();
    }
}
