package com.chestlogger.interop;

import com.chestlogger.container.ContainerSnapshot;
import com.chestlogger.container.SlotSnapshot;
import com.chestlogger.event.*;
import com.chestlogger.index.IndexPointer;
import com.chestlogger.index.IndexQueryFilter;
import com.chestlogger.index.PersistentIndexManager;
import com.chestlogger.query.QueryEngine;
import com.chestlogger.recovery.RecoveryReport;
import com.chestlogger.recovery.TailRecoveryEngine;
import com.chestlogger.rollback.RollbackEngine;
import com.chestlogger.rollback.RollbackPlan;
import com.chestlogger.rollback.RollbackResult;
import com.chestlogger.storage.*;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("Cross-Platform Binary Interoperability & Rollback Tests")
class CrossPlatformBinaryInteroperabilityTest {

    @Test
    @DisplayName("Logs generated by Paper platform should be seamlessly queried and rolled back by Fabric engine")
    void testPaperToFabricInteroperability(@TempDir File sharedLogDir) throws IOException {
        BlockCompressor compressor = new LZ4BlockCompressor();
        StringTableDictionary stringDictionary = new StringTableDictionary();
        StorageProfile profile = StorageProfile.BALANCED;

        UUID playerUuid = UUID.fromString("11111111-2222-3333-4444-555555555555");
        long chestPos = BlockPosUtil.pack(100, 64, -200);
        String dimension = "minecraft:overworld";

        // Step 1: Simulate Paper Plugin generating transaction events
        List<TransactionLogEntry> paperGeneratedEntries = new ArrayList<>();
        paperGeneratedEntries.add(new TransactionLogEntry(
                1L,
                1700000000000L,
                UUID.randomUUID(),
                ActionType.PICKUP,
                ActorType.PLAYER,
                playerUuid,
                "PaperPlayer",
                dimension,
                chestPos,
                List.of(new SlotDelta(0, "minecraft:diamond", -32, 64, 32, 0L))
        ));

        paperGeneratedEntries.add(new TransactionLogEntry(
                2L,
                1700000001000L,
                UUID.randomUUID(),
                ActionType.SHIFT_CLICK_INSERT,
                ActorType.PLAYER,
                playerUuid,
                "PaperPlayer",
                dimension,
                chestPos,
                List.of(new SlotDelta(1, "minecraft:gold_ingot", 16, 0, 16, 12345L))
        ));

        // Write with Paper-configured segment writer
        try (LogSegmentWriter paperWriter = new LogSegmentWriter(sharedLogDir, "chestlog", 0, 1L, compressor, profile, stringDictionary)) {
            paperWriter.writeBatch(paperGeneratedEntries);
        }

        // Step 2: Simulate Fabric Mod inspecting, indexing, and querying the shared log directory
        PersistentIndexManager fabricIndex = new PersistentIndexManager(sharedLogDir);
        for (int i = 0; i < paperGeneratedEntries.size(); i++) {
            TransactionLogEntry entry = paperGeneratedEntries.get(i);
            fabricIndex.index(new IndexPointer(
                    entry.sequenceId(),
                    entry.timestampMs(),
                    entry.actorUuid(),
                    entry.deltas().get(0).itemId(),
                    entry.dimension(),
                    entry.packedBlockPos(),
                    0,
                    32L,
                    i
            ));
        }

        QueryEngine fabricQueryEngine = new QueryEngine(sharedLogDir, compressor, fabricIndex, () -> stringDictionary);
        List<TransactionLogEntry> queried = fabricQueryEngine.fetchRecords(
                IndexQueryFilter.builder()
                        .dimension(dimension)
                        .exactBlockPos(chestPos)
                        .build()
        );

        assertThat(queried).hasSize(2);
        assertThat(queried.get(0).actorName()).isEqualTo("PaperPlayer");
        assertThat(queried.get(0).deltas().get(0).itemId()).isEqualTo("minecraft:diamond");
        assertThat(queried.get(1).deltas().get(0).itemId()).isEqualTo("minecraft:gold_ingot");

        // Step 3: Simulate Fabric executing a Rollback on container state
        ContainerSnapshot fabricContainer = new ContainerSnapshot(27);
        fabricContainer.setSlot(0, "minecraft:diamond", 32, 0L);
        fabricContainer.setSlot(1, "minecraft:gold_ingot", 16, 12345L);

        RollbackEngine rollbackEngine = new RollbackEngine();
        RollbackPlan plan = rollbackEngine.createPlan(queried, fabricContainer);

        assertThat(plan.hasConflicts()).isFalse();
        assertThat(plan.steps()).hasSize(2);

        TransactionEventQueue auditQueue = new TransactionEventQueue(100);
        RollbackResult result = rollbackEngine.applyRollback(
                plan, fabricContainer, auditQueue, UUID.randomUUID(), "Admin", dimension, chestPos
        );

        assertThat(result.success()).isTrue();
        assertThat(result.appliedSteps()).isEqualTo(2);
        // Restored diamond count: 32 + 32 = 64
        assertThat(fabricContainer.getSlot(0).count()).isEqualTo(64);
        // Removed gold count: 16 - 16 = 0
        assertThat(fabricContainer.getSlot(1).count()).isEqualTo(0);
        assertThat(auditQueue.getDepth()).isEqualTo(1);
    }

    @Test
    @DisplayName("Logs generated by Fabric platform should be seamlessly recovered and indexed by Paper engine")
    void testFabricToPaperInteroperability(@TempDir File sharedLogDir) throws IOException {
        BlockCompressor compressor = new LZ4BlockCompressor();
        StringTableDictionary stringDictionary = new StringTableDictionary();
        StorageProfile profile = StorageProfile.BALANCED;

        UUID playerUuid = UUID.fromString("99999999-8888-7777-6666-555555555555");
        long chestPos = BlockPosUtil.pack(50, 70, 50);
        String dimension = "minecraft:the_nether";

        List<TransactionLogEntry> fabricEntries = List.of(
                new TransactionLogEntry(
                        100L,
                        1700000010000L,
                        UUID.randomUUID(),
                        ActionType.HOPPER_EXTRACT,
                        ActorType.HOPPER_BLOCK,
                        null,
                        "Hopper",
                        dimension,
                        chestPos,
                        List.of(new SlotDelta(5, "minecraft:ancient_debris", -4, 8, 4, 0L))
                )
        );

        // Write from Fabric
        try (LogSegmentWriter fabricWriter = new LogSegmentWriter(sharedLogDir, "chestlog", 0, 100L, compressor, profile, stringDictionary)) {
            fabricWriter.writeBatch(fabricEntries);
        }

        // Recover and validate via Paper recovery engine
        TailRecoveryEngine recovery = new TailRecoveryEngine(compressor);
        RecoveryReport report = recovery.recoverAndValidate(sharedLogDir);

        assertThat(report.hasCorruptions()).isFalse();
        assertThat(report.maxSequenceId()).isEqualTo(100L);

        // Query via Paper
        PersistentIndexManager paperIndex = new PersistentIndexManager(sharedLogDir);
        paperIndex.index(new IndexPointer(100L, 1700000010000L, null, "minecraft:ancient_debris", dimension, chestPos, 0, 32L, 0));

        QueryEngine paperQueryEngine = new QueryEngine(sharedLogDir, compressor, paperIndex, () -> stringDictionary);
        List<TransactionLogEntry> paperMatches = paperQueryEngine.fetchRecords(
                IndexQueryFilter.builder().dimension(dimension).exactBlockPos(chestPos).build()
        );

        assertThat(paperMatches).hasSize(1);
        assertThat(paperMatches.get(0).actionType()).isEqualTo(ActionType.HOPPER_EXTRACT);
        assertThat(paperMatches.get(0).actorType()).isEqualTo(ActorType.HOPPER_BLOCK);
    }
}
